-- AlterTable
ALTER TABLE "User" ADD COLUMN     "badges" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "coin" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "currentBadge" TEXT,
ADD COLUMN     "plan" JSONB,
ADD COLUMN     "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
