import { type Payment } from "./columns";

// Sample payment data
export const paymentsData: Payment[] = [
  {
    id: "1",
    amount: 100.0,
    status: "pending",
    description: "Grocery Store",
    date: "2024-01-15",
    category: "Food",
  },
  {
    id: "2",
    amount: 250.5,
    status: "processing",
    description: "Electricity Bill",
    date: "2024-01-14",
    category: "Utilities",
  },
  {
    id: "3",
    amount: 500.0,
    status: "success",
    description: "Salary Deposit",
    date: "2024-01-13",
    category: "Income",
  },
  {
    id: "4",
    amount: 75.25,
    status: "failed",
    description: "Coffee Shop",
    date: "2024-01-12",
    category: "Food",
  },
  {
    id: "5",
    amount: 1200.0,
    status: "success",
    description: "Rent Payment",
    date: "2024-01-11",
    category: "Housing",
  },
  {
    id: "6",
    amount: 350.75,
    status: "pending",
    description: "Gas Station",
    date: "2024-01-10",
    category: "Transportation",
  },
  {
    id: "7",
    amount: 890.5,
    status: "processing",
    description: "Online Shopping",
    date: "2024-01-09",
    category: "Shopping",
  },
  {
    id: "8",
    amount: 125.0,
    status: "success",
    description: "Restaurant",
    date: "2024-01-08",
    category: "Food",
  },
  {
    id: "9",
    amount: 450.25,
    status: "failed",
    description: "Gym Membership",
    date: "2024-01-07",
    category: "Health",
  },
  {
    id: "10",
    amount: 675.0,
    status: "success",
    description: "Freelance Payment",
    date: "2024-01-06",
    category: "Income",
  },
];

